export const USER_BYID_REQUEST = "USER_BYID_REQUEST";
export const USER_BYID_SUCCESS = "USER_BYID_SUCCESS";
export const USER_BYID_FAIL = "USER_BYID_FAIL";

export const ADMIN_USER_BYID_REQUEST = "ADMIN_USER_BYID_REQUEST";
export const ADMIN_USER_BYID_SUCCESS = "ADMIN_USER_BYID_SUCCESS";
export const ADMIN_USER_BYID_FAIL = "ADMIN_USER_BYID_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const GETALL_USERS_REQUEST = "GETALL_USERS_REQUEST";
export const GETALL_USERS_SUCCESS = "GETALL_USERS_SUCCESS";
export const GETALL_USERS_FAIL = "GETALL_USERS_FAIL";

export const UPDATE_USER_BY_ADMIN_REQUEST = "UPDATE_USER_BY_ADMIN_REQUEST";
export const UPDATE_USER_BY_ADMIN_SUCCESS = "UPDATE_USER_BY_ADMIN_SUCCESS";
export const UPDATE_USER_BY_ADMIN_FAIL = "UPDATE_USER_BY_ADMIN_FAIL";
